package com.wayrapass.service;

import com.wayrapass.dto.request.*; import com.wayrapass.dto.response.*; import com.wayrapass.exception.*; import com.wayrapass.mapper.UserMapper; import com.wayrapass.model.*; import com.wayrapass.repository.*; import com.wayrapass.security.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.security.authentication.*; import org.springframework.security.core.AuthenticationException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*;

@Service
public class AuthService {
 private static final int MAX_ATTEMPTS=3; private static final long LOCK_SECONDS=300;
 private final UserRepository users; private final StudentRepository students; private final InstitutionRepository institutions; private final PasswordResetTokenRepository resetTokens; private final PasswordEncoder passwords; private final AuthenticationManager authenticationManager; private final JwtService jwt; private final UserMapper mapper; private final boolean exposeResetToken;
 public AuthService(UserRepository users,StudentRepository students,InstitutionRepository institutions,PasswordResetTokenRepository resetTokens,PasswordEncoder passwords,AuthenticationManager authenticationManager,JwtService jwt,UserMapper mapper,@Value("${app.password-reset.expose-development-token:true}") boolean exposeResetToken){this.users=users;this.students=students;this.institutions=institutions;this.resetTokens=resetTokens;this.passwords=passwords;this.authenticationManager=authenticationManager;this.jwt=jwt;this.mapper=mapper;this.exposeResetToken=exposeResetToken;}
 @Transactional public AuthResponseDTO register(UserRequestDTO r){
  Role role=r.role()==null?Role.STUDENT:r.role(); if(role!=Role.STUDENT&&role!=Role.FAMILY)throw new BusinessRuleException("El registro público solo admite STUDENT o FAMILY.");
  String email=normalize(r.email()); if(users.existsByEmailIgnoreCase(email))throw new ConflictException("El correo ya está registrado.");
  User u=new User();u.setFullName(r.fullName().trim());u.setEmail(email);u.setPasswordHash(passwords.encode(r.password()));u.setPhone(blankToNull(r.phone()));u.setRole(role);u.setEnabled(true);users.save(u);
  if(role==Role.STUDENT){if(r.institutionId()==null)throw new BusinessRuleException("institutionId es obligatorio para estudiantes.");Institution i=institutions.findById(r.institutionId()).orElseThrow(()->new ResourceNotFoundException("Institución no encontrada."));if(r.studentCode()!=null&&students.existsByInstitutionIdAndStudentCodeIgnoreCase(i.getId(),r.studentCode().trim()))throw new ConflictException("El código estudiantil ya existe en la institución.");Student s=new Student();s.setUser(u);s.setInstitution(i);s.setStudentCode(blankToNull(r.studentCode()));students.save(s);}
  return response(u);
 }
 @Transactional(noRollbackFor={UnauthorizedException.class,AccountLockedException.class}) public AuthResponseDTO login(LoginRequestDTO r){
  User u=users.findByEmailIgnoreCase(normalize(r.email())).orElseThrow(()->new UnauthorizedException("Correo o contraseña incorrectos."));Instant now=Instant.now();
  if(!u.isEnabled())throw new UnauthorizedException("La cuenta está deshabilitada."); if(u.getLockedUntil()!=null&&u.getLockedUntil().isAfter(now))throw new AccountLockedException("La cuenta está bloqueada temporalmente."); if(u.getLockedUntil()!=null){u.setLockedUntil(null);u.setFailedLoginAttempts(0);}
  try{authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(u.getEmail(),r.password()));}catch(AuthenticationException e){int n=u.getFailedLoginAttempts()+1;u.setFailedLoginAttempts(n);if(n>=MAX_ATTEMPTS){u.setFailedLoginAttempts(0);u.setLockedUntil(now.plusSeconds(LOCK_SECONDS));users.save(u);throw new AccountLockedException("La cuenta fue bloqueada durante 5 minutos.");}users.save(u);throw new UnauthorizedException("Correo o contraseña incorrectos.");}
  u.setFailedLoginAttempts(0);u.setLockedUntil(null);users.save(u);return response(u);
 }
 @Transactional public PasswordResetResponse forgotPassword(ForgotPasswordRequest r){Optional<User> found=users.findByEmailIgnoreCase(normalize(r.email()));if(found.isEmpty())return new PasswordResetResponse("Si el correo existe, se generó un enlace de recuperación.",null);byte[] bytes=new byte[32];new SecureRandom().nextBytes(bytes);String plain=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);PasswordResetToken t=new PasswordResetToken();t.setUser(found.get());t.setTokenHash(hash(plain));t.setExpiresAt(Instant.now().plusSeconds(900));resetTokens.save(t);return new PasswordResetResponse("Si el correo existe, se generó un enlace de recuperación.",exposeResetToken?plain:null);}
 @Transactional public void resetPassword(ResetPasswordRequest r){PasswordResetToken t=resetTokens.findByTokenHash(hash(r.token())).orElseThrow(()->new BusinessRuleException("Token inválido o vencido."));Instant n=Instant.now();if(t.getUsedAt()!=null||!t.getExpiresAt().isAfter(n))throw new BusinessRuleException("Token inválido o vencido.");t.getUser().setPasswordHash(passwords.encode(r.newPassword()));t.setUsedAt(n);resetTokens.save(t);users.save(t.getUser());}
 private AuthResponseDTO response(User u){return new AuthResponseDTO(jwt.generate(UserPrincipal.from(u)),"Bearer",mapper.toResponse(u));}
 private static String normalize(String s){return s.trim().toLowerCase(Locale.ROOT);} private static String blankToNull(String s){return s==null||s.isBlank()?null:s.trim();}
 private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
