package com.wayrapass.service;
import com.wayrapass.dto.request.CatalogRequests; import com.wayrapass.dto.response.CatalogResponses; import com.wayrapass.exception.*; import com.wayrapass.model.*; import com.wayrapass.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor public class CatalogService {
 private final InstitutionRepository institutions;private final RouteRepository routes;private final StopRepository stops;private final RouteScheduleRepository schedules;private final VehicleRepository vehicles;private final RouteStopRepository routeStops;
 @Transactional(readOnly=true) public List<CatalogResponses.Institution> institutions(){return institutions.findAll().stream().map(this::out).toList();} @Transactional(readOnly=true) public CatalogResponses.Institution institution(Long id){return out(institutionEntity(id));}
 @Transactional public CatalogResponses.Institution saveInstitution(Long id,CatalogRequests.Institution r){Institution x=id==null?new Institution():institutionEntity(id);x.setName(r.name().trim());x.setCampusName(trim(r.campusName()));x.setAddress(trim(r.address()));x.setDistrict(trim(r.district()));x.setActive(r.active());return out(institutions.save(x));} @Transactional public void deleteInstitution(Long id){institutions.delete(institutionEntity(id));}
 @Transactional(readOnly=true) public List<CatalogResponses.Route> routes(){return routes.findAll().stream().map(this::out).toList();} @Transactional(readOnly=true) public CatalogResponses.Route route(Long id){return out(routeEntity(id));}
 @Transactional public CatalogResponses.Route saveRoute(Long id,CatalogRequests.Route r){Route x=id==null?new Route():routeEntity(id);if(id==null&&routes.existsByCodeIgnoreCase(r.code()))throw new ConflictException("El código de ruta ya existe.");x.setInstitution(institutionEntity(r.institutionId()));x.setCode(r.code().trim().toUpperCase());x.setName(r.name().trim());x.setOrigin(r.origin().trim());x.setDestination(r.destination().trim());x.setDescription(trim(r.description()));x.setStatus(r.status());return out(routes.save(x));} @Transactional public void deleteRoute(Long id){routes.delete(routeEntity(id));}
 @Transactional(readOnly=true) public List<CatalogResponses.Stop> stops(){return stops.findAll().stream().map(this::out).toList();} @Transactional(readOnly=true) public CatalogResponses.Stop stop(Long id){return out(stopEntity(id));}
 @Transactional public CatalogResponses.Stop saveStop(Long id,CatalogRequests.Stop r){Stop x=id==null?new Stop():stopEntity(id);x.setName(r.name().trim());x.setAddress(trim(r.address()));x.setDistrict(trim(r.district()));x.setLatitude(r.latitude());x.setLongitude(r.longitude());x.setActive(r.active());return out(stops.save(x));} @Transactional public void deleteStop(Long id){stops.delete(stopEntity(id));}
 @Transactional(readOnly=true) public List<CatalogResponses.Schedule> schedules(){return schedules.findAll().stream().map(this::out).toList();} @Transactional(readOnly=true) public CatalogResponses.Schedule schedule(Long id){return out(scheduleEntity(id));}
 @Transactional public CatalogResponses.Schedule saveSchedule(Long id,CatalogRequests.Schedule r){RouteSchedule x=id==null?new RouteSchedule():scheduleEntity(id);x.setRoute(routeEntity(r.routeId()));x.setDayOfWeek(r.dayOfWeek());x.setDepartureTime(r.departureTime());x.setEstimatedArrivalTime(r.estimatedArrivalTime());x.setActive(r.active());return out(schedules.save(x));} @Transactional public void deleteSchedule(Long id){schedules.delete(scheduleEntity(id));}
 @Transactional(readOnly=true) public List<CatalogResponses.RouteStop> routeStops(Long routeId){return routeStops.findByRouteIdOrderByStopOrder(routeId).stream().map(this::out).toList();}@Transactional public CatalogResponses.RouteStop saveRouteStop(Long id,CatalogRequests.RouteStop r){RouteStop x=id==null?new RouteStop():routeStops.findById(id).orElseThrow(()->new ResourceNotFoundException("Parada de ruta no encontrada."));x.setRoute(routeEntity(r.routeId()));x.setStop(stopEntity(r.stopId()));x.setStopOrder(r.stopOrder());x.setEstimatedMinutesFromStart(r.estimatedMinutesFromStart());x.setActive(r.active());return out(routeStops.save(x));}@Transactional public void deleteRouteStop(Long id){routeStops.deleteById(id);}
 @Transactional(readOnly=true) public List<CatalogResponses.Vehicle> vehicles(){return vehicles.findAll().stream().map(this::out).toList();} @Transactional(readOnly=true) public CatalogResponses.Vehicle vehicle(Long id){return out(vehicleEntity(id));}
 @Transactional public CatalogResponses.Vehicle saveVehicle(Long id,CatalogRequests.Vehicle r){Vehicle x=id==null?new Vehicle():vehicleEntity(id);if(id==null&&vehicles.existsByPlateIgnoreCase(r.plate()))throw new ConflictException("La placa ya existe.");x.setPlate(r.plate().trim().toUpperCase());x.setBrand(trim(r.brand()));x.setModel(trim(r.model()));x.setCapacity(r.capacity());x.setQrToken(r.qrToken()==null||r.qrToken().isBlank()?UUID.randomUUID().toString():r.qrToken().trim());x.setAuthorizationStatus(r.authorizationStatus());x.setOperationalStatus(r.operationalStatus());return out(vehicles.save(x));} @Transactional public void deleteVehicle(Long id){vehicles.delete(vehicleEntity(id));}
 private Institution institutionEntity(Long id){return institutions.findById(id).orElseThrow(()->new ResourceNotFoundException("Institución no encontrada."));}private Route routeEntity(Long id){return routes.findById(id).orElseThrow(()->new ResourceNotFoundException("Ruta no encontrada."));}private Stop stopEntity(Long id){return stops.findById(id).orElseThrow(()->new ResourceNotFoundException("Paradero no encontrado."));}private RouteSchedule scheduleEntity(Long id){return schedules.findById(id).orElseThrow(()->new ResourceNotFoundException("Horario no encontrado."));}private Vehicle vehicleEntity(Long id){return vehicles.findById(id).orElseThrow(()->new ResourceNotFoundException("Vehículo no encontrado."));}
 private CatalogResponses.Institution out(Institution x){return new CatalogResponses.Institution(x.getId(),x.getName(),x.getCampusName(),x.getAddress(),x.getDistrict(),x.isActive(),x.getCreatedAt());}private CatalogResponses.Route out(Route x){return new CatalogResponses.Route(x.getId(),x.getInstitution().getId(),x.getCode(),x.getName(),x.getOrigin(),x.getDestination(),x.getDescription(),x.getStatus());}private CatalogResponses.Stop out(Stop x){return new CatalogResponses.Stop(x.getId(),x.getName(),x.getAddress(),x.getDistrict(),x.getLatitude(),x.getLongitude(),x.isActive());}private CatalogResponses.Schedule out(RouteSchedule x){return new CatalogResponses.Schedule(x.getId(),x.getRoute().getId(),x.getDayOfWeek(),x.getDepartureTime(),x.getEstimatedArrivalTime(),x.isActive());}private CatalogResponses.RouteStop out(RouteStop x){return new CatalogResponses.RouteStop(x.getId(),x.getRoute().getId(),x.getStop().getId(),x.getStopOrder(),x.getEstimatedMinutesFromStart(),x.isActive());}private CatalogResponses.Vehicle out(Vehicle x){return new CatalogResponses.Vehicle(x.getId(),x.getPlate(),x.getBrand(),x.getModel(),x.getCapacity(),x.getQrToken(),x.getAuthorizationStatus(),x.getOperationalStatus());}private static String trim(String s){return s==null||s.isBlank()?null:s.trim();}
}
