package com.wayrapass.service;
import com.wayrapass.dto.request.DriverRequest; import com.wayrapass.dto.response.DriverResponse; import com.wayrapass.exception.*; import com.wayrapass.model.*; import com.wayrapass.repository.*; import com.wayrapass.security.CurrentUser; import lombok.RequiredArgsConstructor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor public class DriverService {
 private final DriverRepository drivers; private final UserRepository users; private final PasswordEncoder encoder; private final CurrentUser current;
 @Transactional(readOnly=true) public List<DriverResponse> all(){return drivers.findAllByOrderByIdAsc().stream().map(this::out).toList();}
 @Transactional(readOnly=true) public DriverResponse one(Long id){return out(get(id));}
 @Transactional(readOnly=true) public DriverResponse me(){return out(drivers.findByUserId(current.id()).orElseThrow(()->new ResourceNotFoundException("Perfil de conductor no encontrado.")));}
 @Transactional public DriverResponse create(DriverRequest r){if(r.password()==null)throw new BusinessRuleException("password es obligatorio al crear un conductor.");if(users.existsByEmailIgnoreCase(r.email()))throw new ConflictException("El correo ya existe.");if(drivers.existsByLicenseNumberIgnoreCase(r.licenseNumber()))throw new ConflictException("La licencia ya existe.");User u=new User();u.setFullName(r.fullName().trim());u.setEmail(r.email().trim().toLowerCase());u.setPhone(trim(r.phone()));u.setPasswordHash(encoder.encode(r.password()));u.setRole(Role.DRIVER);u.setEnabled(true);users.save(u);Driver d=new Driver();d.setUser(u);apply(d,r);return out(drivers.save(d));}
 @Transactional public DriverResponse update(Long id,DriverRequest r){Driver d=get(id);if(drivers.existsByLicenseNumberIgnoreCaseAndIdNot(r.licenseNumber(),id))throw new ConflictException("La licencia ya existe.");apply(d,r);d.getUser().setFullName(r.fullName().trim());d.getUser().setPhone(trim(r.phone()));return out(d);}
 @Transactional public void delete(Long id){Driver d=get(id);d.getUser().setEnabled(false);d.setOperationalStatus(DriverOperationalStatus.INACTIVE);}
 private Driver get(Long id){return drivers.findById(id).orElseThrow(()->new ResourceNotFoundException("Conductor no encontrado."));} private void apply(Driver d,DriverRequest r){d.setLicenseNumber(r.licenseNumber().trim().toUpperCase());d.setLicenseCategory(r.licenseCategory().trim());d.setLicenseExpiration(r.licenseExpiration());d.setCredentialImageUrl(trim(r.credentialImageUrl()));d.setAuthorizationStatus(r.authorizationStatus());d.setOperationalStatus(r.operationalStatus());}
 private DriverResponse out(Driver d){User u=d.getUser();return new DriverResponse(d.getId(),u.getId(),u.getFullName(),u.getEmail(),u.getPhone(),d.getLicenseNumber(),d.getLicenseCategory(),d.getLicenseExpiration(),d.getCredentialImageUrl(),d.getAuthorizationStatus(),d.getOperationalStatus(),d.getCreatedAt(),d.getUpdatedAt());} private static String trim(String s){return s==null||s.isBlank()?null:s.trim();}
}
