package com.wayrapass.service;
import com.wayrapass.dto.request.OperationalRequests;import com.wayrapass.dto.response.OperationalResponses;import com.wayrapass.exception.*;import com.wayrapass.model.*;import com.wayrapass.repository.*;import com.wayrapass.security.CurrentUser;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class StudentAccessService{
 private final CurrentUser current;private final StudentRepository students;private final StudentFamilyLinkRepository links;private final RouteRepository routes;private final StopRepository stops;private final RouteStopRepository routeStops;private final StudentRouteEnrollmentRepository enrollments;private final FavoriteRouteRepository favorites;
 @Transactional public OperationalResponses.FamilyCode generateCode(){Student s=myStudent();String code="%06d".formatted(new SecureRandom().nextInt(1_000_000));s.setFamilyLinkCodeHash(hash(code));s.setFamilyLinkCodeExpiresAt(Instant.now().plusSeconds(600));return new OperationalResponses.FamilyCode(code,s.getFamilyLinkCodeExpiresAt());}
 @Transactional public void linkFamily(Long studentId,OperationalRequests.FamilyCode r){User family=current.require();if(family.getRole()!=Role.FAMILY)throw new org.springframework.security.access.AccessDeniedException("Solo FAMILY");Student s=students.findById(studentId).orElseThrow(()->new ResourceNotFoundException("Estudiante no encontrado."));if(s.getFamilyLinkCodeHash()==null||s.getFamilyLinkCodeExpiresAt()==null||!s.getFamilyLinkCodeExpiresAt().isAfter(Instant.now())||!MessageDigest.isEqual(s.getFamilyLinkCodeHash().getBytes(StandardCharsets.UTF_8),hash(r.code()).getBytes(StandardCharsets.UTF_8)))throw new BusinessRuleException("Código de vinculación inválido o vencido.");StudentFamilyLink l=links.findByStudentIdAndFamilyUserId(studentId,family.getId()).orElseGet(StudentFamilyLink::new);l.setStudent(s);l.setFamilyUser(family);l.setRelationship(r.relationship());l.setAuthorized(true);l.setRevokedAt(null);links.save(l);s.setFamilyLinkCodeHash(null);s.setFamilyLinkCodeExpiresAt(null);}
 @Transactional public OperationalResponses.Enrollment enroll(OperationalRequests.Enrollment r){Student s=myStudent();if(!routeStops.existsByRouteIdAndStopId(r.routeId(),r.stopId()))throw new BusinessRuleException("El paradero no pertenece a la ruta.");var currentEnrollment=enrollments.findCurrentForUpdate(s.getId(),List.of(EnrollmentStatus.ACTIVE,EnrollmentStatus.SUSPENDED));currentEnrollment.ifPresent(e->{e.setStatus(EnrollmentStatus.ENDED);e.setValidUntil(LocalDate.now());});StudentRouteEnrollment e=new StudentRouteEnrollment();e.setStudent(s);e.setRoute(routes.findById(r.routeId()).orElseThrow(()->new ResourceNotFoundException("Ruta no encontrada.")));e.setStop(stops.findById(r.stopId()).orElseThrow(()->new ResourceNotFoundException("Paradero no encontrado.")));return out(enrollments.save(e));}
 @Transactional public void favorite(Long routeId){Student s=myStudent();Route r=routes.findById(routeId).orElseThrow(()->new ResourceNotFoundException("Ruta no encontrada."));FavoriteRoute f=new FavoriteRoute();f.setStudent(s);f.setRoute(r);favorites.save(f);}@Transactional public void unfavorite(Long routeId){favorites.deleteById(new FavoriteRouteId(myStudent().getId(),routeId));}
 @Transactional(readOnly=true) public List<Long> favorites(){return favorites.findByStudentId(myStudent().getId()).stream().map(f->f.getRoute().getId()).toList();}
 @Transactional(readOnly=true) public List<Long> familyStudents(){User u=current.require();if(u.getRole()!=Role.FAMILY)throw new org.springframework.security.access.AccessDeniedException("Solo FAMILY");return links.findByFamilyUserIdAndAuthorizedTrue(u.getId()).stream().map(l->l.getStudent().getId()).toList();}
 public void requireStudentAccess(Long studentId){User u=current.require();if(u.getRole()==Role.COORDINATOR)return;if(u.getRole()==Role.STUDENT&&students.findByUserId(u.getId()).map(Student::getId).filter(studentId::equals).isPresent())return;if(u.getRole()==Role.FAMILY&&links.existsByStudentIdAndFamilyUserIdAndAuthorizedTrue(studentId,u.getId()))return;throw new org.springframework.security.access.AccessDeniedException("Sin acceso al estudiante.");}
 private Student myStudent(){User u=current.require();if(u.getRole()!=Role.STUDENT)throw new org.springframework.security.access.AccessDeniedException("Solo STUDENT");return students.findByUserId(u.getId()).orElseThrow(()->new ResourceNotFoundException("Perfil estudiantil no encontrado."));}private OperationalResponses.Enrollment out(StudentRouteEnrollment e){return new OperationalResponses.Enrollment(e.getId(),e.getStudent().getId(),e.getRoute().getId(),e.getStop().getId(),e.getStatus(),e.getValidFrom(),e.getValidUntil());}private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
